---
- name: Install Munge packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ munge_packages }}"
  tags: munge_install

- name: Create munge user
  user:
    name: munge
    system: yes
    shell: /bin/false
    state: present
  tags: munge_user

- name: Create Munge directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: munge
    group: munge
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/munge', mode: '0700' }
    - { path: '/var/lib/munge', mode: '0700' }
    - { path: '/var/log/munge', mode: '0755' }
  tags: munge_directories

- name: Copy munge.key from project root to all nodes
  copy:
    src: ../../munge.key  # Path from role to project root
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
    backup: yes
  notify: restart munge
  tags: munge_key

- name: Enable and start munge service
  systemd:
    name: munge
    enabled: yes
    state: started
  tags: munge_service
